### ISSUE TITLE
タスク作成時に完了が押せてしまう

### ISSUE THREAD

**Issue by Hosi121** [Hosi121/todoApp#22]
### Who do?

@xhogo 

### As Is

タイトル通り

### To Be

いい感じに直す

### Action

fix/complete-buttonのブランチで作業して，終わったらレビューを受けマージ

### content Check

- [X] I agree to follow this project's Code of Conduct

**Comment by shgnaka** [comment]
次の問題があると思います．

### 事実
1：タスク作成モーダルが存在しない．
2：タスク作成ボタンから開かれるモーダルが，タスク編集のモーダルである．

### 発生する問題
1：タスク作成時に完了ボタンが押せる．
2：タスク作成なのに「編集」と表示されている．

次の解決案を考えました．

### 解決案
1：タスク作成モーダルを作成する．
2：既存のタスク編集コンポーネントを再利用性を高めて再設計する．（つまり，タスク作成と編集が切り替えれるようにする）
2.1：その場合，ファイル名が命名違反するので変更推奨．

いづれにせよ，ひねが担当しているissue( #21 )に影響が出るので，仕様の再定義が必要だと思います．

PMであるひらくさん（ @Shiluco  ）に決定していただきたいです．

**Comment by Shiluco** [comment]
@xhogo の解決案を採用します。
担当も @xhogo にお願いします。

提案された解決案に則って修正お願いします。
編集の時に用いたコンポーネントを再利用してタスク作成モーダルを作ってほしいです。
デザインの修正の #21 に関して宣言するcssのclassまたはidが変わりますが対処可能なので #21 は #22 に則って設計するものとします。
